SELECT *
FROM PAYMENT
WHERE TYPE_ID = 'MONTHLY';

SELECT MARK
FROM MARK
WHERE SUBJECT_ID = 'Art';

SELECT STUDENT_ID
FROM PAYMENT
WHERE TYPE_ID = 'WEEKLY';

SELECT STUDENT_ID
FROM MARK
WHERE SUBJECT_ID = 'Math'