DELETE FROM STUDENT WHERE id IN ( SELECT id FROM student WHERE STUDENT.GROUPNUMBER >= 4 );
DELETE FROM PAYMENT WHERE student_id IN ( SELECT id FROM student WHERE STUDENT.GROUPNUMBER >= 4 );
DELETE FROM MARK WHERE student_id IN ( SELECT id FROM student WHERE STUDENT.GROUPNUMBER >= 4 );
DELETE FROM STUDENT WHERE id IN (SELECT student_id FROM mark WHERE mark < 4);
DELETE FROM PAYMENT WHERE student_id IN ( SELECT student_id FROM mark WHERE mark < 4 );
DELETE FROM MARK WHERE mark < 4;
DELETE FROM PAYMENTTYPE WHERE name = 'Daily';
DELETE FROM PAYMENT WHERE type_id IN ( SELECT id FROM paymenttype WHERE name = 'Daily');
DELETE FROM MARK WHERE mark < 7;