SELECT * FROM PAYMENT WHERE AMOUNT >= 500;

SELECT * FROM Student WHERE DATEDIFF('YEAR', birthday, CURRENT_DATE) > 20;

SELECT * FROM STUDENT WHERE GROUPNUMBER = 10 AND DATEDIFF('YEAR', birthday, CURRENT_DATE) < 20;

SELECT * FROM STUDENT WHERE NAME = 'Mike' OR GROUPNUMBER = 4 OR GROUPNUMBER = 5 OR GROUPNUMBER = 6;

SELECT * FROM PAYMENT WHERE DATEDIFF('MONTH', PAYMENT_DATE, CURRENT_DATE) < 8;

SELECT * FROM STUDENT WHERE NAME LIKE 'A%';

SELECT * FROM STUDENT WHERE (NAME = 'ROXI' AND GROUPNUMBER = 4) OR (NAME = 'Tallie' AND GROUPNUMBER = 9);