ALTER TABLE STUDENT MODIFY COLUMN birthday DATE NOT NULL;
ALTER TABLE mark MODIFY COLUMN mark INT NOT NULL CHECK (mark >= 1 AND mark <= 10);
ALTER TABLE mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject MODIFY COLUMN grade INT NOT NULL CHECK (grade >= 1 AND grade <= 5);
ALTER TABLE paymenttype ADD UNIQUE (name);
ALTER TABLE payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount DECIMAL(10, 2) NOT NULL;
ALTER TABLE payment MODIFY COLUMN payment_date DATETIME NOT NULL;